language: c
before_install:
install:
  - sudo apt-get install valgrind
  - sudo make install --file=linux.makefile
script:
  - cd ex_parcels
  - make valgrind --file=linux.makefile
  - cd .. 
after_script: